import { EstadoAlerta, Franquicia, type Alerta, type FaseProceso, type MetricaKPI } from "@/types";

export const volumetriaBdB = {
  alertasMensuales: 700000,
  alertasGestionadasActualmente: {
    min: 20000,
    max: 30000,
  },
  clientesImpactados: 250000,
  personalOperativo: 50,
  falsosPositivos: {
    min: 70,
    max: 80,
  },
  tiempoPromedioRespuestaMinutos: 40,
  contactabilidadWhatsApp: 70,
  operacion: "24/7/365",
  sistemas: [
    "Monitor",
    "VRM (Visa)",
    "EMS/MS (Mastercard)",
    "Cardinal",
    "CRM Banco",
    "Kari AI",
    "PPE",
  ],
} as const;

export const faseProcesoBdB: FaseProceso = {
  recepcion: 35,
  identificacion: 22,
  comunicacion: 18,
  decision: 15,
  registro: 10,
};

export const kpiData: MetricaKPI[] = [
  {
    label: "Alertas mensuales",
    valor: 700000,
    tendencia: "+18% respecto al mes anterior",
    icono: "activity",
    color: "cyan",
  },
  {
    label: "Gestionadas actualmente",
    valor: "20.000 - 30.000",
    tendencia: "Cobertura operativa parcial",
    icono: "layers",
    color: "blue",
  },
  {
    label: "Clientes impactados",
    valor: 250000,
    tendencia: "Volumen sensible acumulado",
    icono: "users",
    color: "emerald",
  },
  {
    label: "Falsos positivos",
    valor: "70% - 80%",
    tendencia: "Alta fricción operativa",
    icono: "shield-alert",
    color: "amber",
  },
  {
    label: "Tiempo respuesta",
    valor: "40 min",
    tendencia: "Promedio actual de gestión",
    icono: "timer",
    color: "red",
  },
];

const fechaBase = new Date("2026-05-25T08:00:00-05:00");

function fechaRelativa(minutesAgo: number): string {
  return new Date(fechaBase.getTime() - minutesAgo * 60_000).toISOString();
}

export const mockAlerts: Alerta[] = [
  {
    id: "ALT-2026-00001",
    franquicia: Franquicia.VISA,
    tarjeta: "**** **** **** 4821",
    monto: 1280000,
    estado: EstadoAlerta.PENDIENTE_REVISION,
    tiempo: "2 min",
    cliente: "Juan Sebastián Rojas",
    area: "Monitor",
    fecha: fechaRelativa(2),
  },
  {
    id: "ALT-2026-00002",
    franquicia: Franquicia.MASTERCARD,
    tarjeta: "**** **** **** 9034",
    monto: 8750000,
    estado: EstadoAlerta.EN_VERIFICACION_CRM,
    tiempo: "15 min",
    cliente: "Laura Sofía Gómez",
    area: "CRM",
    fecha: fechaRelativa(15),
  },
  {
    id: "ALT-2026-00003",
    franquicia: Franquicia.MONITOR,
    tarjeta: "**** **** **** 1176",
    monto: 215000,
    estado: EstadoAlerta.WHATSAPP_ENVIADO,
    tiempo: "38 min",
    cliente: "Andrés Felipe Cárdenas",
    area: "Kari AI",
    fecha: fechaRelativa(38),
  },
  {
    id: "ALT-2026-00004",
    franquicia: Franquicia.VISA,
    tarjeta: "**** **** **** 7740",
    monto: 1543000,
    estado: EstadoAlerta.ESPERANDO_CLIENTE,
    tiempo: "1h 20m",
    cliente: "Catalina María Moreno",
    area: "PPE",
    fecha: fechaRelativa(80),
  },
  {
    id: "ALT-2026-00005",
    franquicia: Franquicia.MASTERCARD,
    tarjeta: "**** **** **** 5208",
    monto: 6500000,
    estado: EstadoAlerta.BLOQUEO_PREVENTIVO,
    tiempo: "6 min",
    cliente: "Daniel Esteban Pérez",
    area: "VRM",
    fecha: fechaRelativa(6),
  },
  {
    id: "ALT-2026-00006",
    franquicia: Franquicia.VISA,
    tarjeta: "**** **** **** 3389",
    monto: 980000,
    estado: EstadoAlerta.DESBLOQUEADO,
    tiempo: "54 min",
    cliente: "Paula Andrea Díaz",
    area: "CRM",
    fecha: fechaRelativa(54),
  },
  {
    id: "ALT-2026-00007",
    franquicia: Franquicia.MONITOR,
    tarjeta: "**** **** **** 6114",
    monto: 14200000,
    estado: EstadoAlerta.BLOQUEO_DEFINITIVO,
    tiempo: "3h 05m",
    cliente: "Miguel Ángel Torres",
    area: "Cardinal",
    fecha: fechaRelativa(185),
  },
  {
    id: "ALT-2026-00008",
    franquicia: Franquicia.MASTERCARD,
    tarjeta: "**** **** **** 9055",
    monto: 420000,
    estado: EstadoAlerta.TIPIFICADO,
    tiempo: "22 min",
    cliente: "Valentina Salazar",
    area: "PPE",
    fecha: fechaRelativa(22),
  },
  {
    id: "ALT-2026-00009",
    franquicia: Franquicia.VISA,
    tarjeta: "**** **** **** 1942",
    monto: 3500000,
    estado: EstadoAlerta.PENDIENTE_REVISION,
    tiempo: "4 min",
    cliente: "Sebastián Herrera",
    area: "Monitor",
    fecha: fechaRelativa(4),
  },
  {
    id: "ALT-2026-00010",
    franquicia: Franquicia.MASTERCARD,
    tarjeta: "**** **** **** 8701",
    monto: 590000,
    estado: EstadoAlerta.EN_VERIFICACION_CRM,
    tiempo: "31 min",
    cliente: "Daniela Castro",
    area: "CRM",
    fecha: fechaRelativa(31),
  },
  {
    id: "ALT-2026-00011",
    franquicia: Franquicia.MONITOR,
    tarjeta: "**** **** **** 2477",
    monto: 7100000,
    estado: EstadoAlerta.WHATSAPP_ENVIADO,
    tiempo: "12 min",
    cliente: "Carlos Andrés Méndez",
    area: "Kari AI",
    fecha: fechaRelativa(12),
  },
  {
    id: "ALT-2026-00012",
    franquicia: Franquicia.VISA,
    tarjeta: "**** **** **** 6638",
    monto: 870000,
    estado: EstadoAlerta.ESPERANDO_CLIENTE,
    tiempo: "46 min",
    cliente: "Mariana Rincón",
    area: "PPE",
    fecha: fechaRelativa(46),
  },
  {
    id: "ALT-2026-00013",
    franquicia: Franquicia.MASTERCARD,
    tarjeta: "**** **** **** 1180",
    monto: 14900000,
    estado: EstadoAlerta.BLOQUEO_PREVENTIVO,
    tiempo: "8 min",
    cliente: "Felipe Camacho",
    area: "VRM",
    fecha: fechaRelativa(8),
  },
  {
    id: "ALT-2026-00014",
    franquicia: Franquicia.VISA,
    tarjeta: "**** **** **** 5092",
    monto: 5250000,
    estado: EstadoAlerta.DESBLOQUEADO,
    tiempo: "2h 10m",
    cliente: "Laura Vanessa Rueda",
    area: "CRM",
    fecha: fechaRelativa(130),
  },
  {
    id: "ALT-2026-00015",
    franquicia: Franquicia.MONITOR,
    tarjeta: "**** **** **** 7331",
    monto: 990000,
    estado: EstadoAlerta.BLOQUEO_DEFINITIVO,
    tiempo: "1h 05m",
    cliente: "Julián Andrés Solano",
    area: "Cardinal",
    fecha: fechaRelativa(65),
  },
  {
    id: "ALT-2026-00016",
    franquicia: Franquicia.MASTERCARD,
    tarjeta: "**** **** **** 4450",
    monto: 730000,
    estado: EstadoAlerta.TIPIFICADO,
    tiempo: "17 min",
    cliente: "Natalia Giraldo",
    area: "PPE",
    fecha: fechaRelativa(17),
  },
  {
    id: "ALT-2026-00017",
    franquicia: Franquicia.VISA,
    tarjeta: "**** **** **** 2804",
    monto: 2800000,
    estado: EstadoAlerta.PENDIENTE_REVISION,
    tiempo: "9 min",
    cliente: "Santiago Ríos",
    area: "Monitor",
    fecha: fechaRelativa(9),
  },
  {
    id: "ALT-2026-00018",
    franquicia: Franquicia.MASTERCARD,
    tarjeta: "**** **** **** 5629",
    monto: 410000,
    estado: EstadoAlerta.EN_VERIFICACION_CRM,
    tiempo: "28 min",
    cliente: "Camila Pardo",
    area: "CRM",
    fecha: fechaRelativa(28),
  },
  {
    id: "ALT-2026-00019",
    franquicia: Franquicia.MONITOR,
    tarjeta: "**** **** **** 8146",
    monto: 11200000,
    estado: EstadoAlerta.WHATSAPP_ENVIADO,
    tiempo: "41 min",
    cliente: "Tomás Echeverry",
    area: "Kari AI",
    fecha: fechaRelativa(41),
  },
  {
    id: "ALT-2026-00020",
    franquicia: Franquicia.VISA,
    tarjeta: "**** **** **** 1967",
    monto: 560000,
    estado: EstadoAlerta.TIPIFICADO,
    tiempo: "55 min",
    cliente: "Isabella Fajardo",
    area: "PPE",
    fecha: fechaRelativa(55),
  },
];